[package]
name = "rando-rust"
version = "0.1.0"
authors = ["pancelor <pancelor@gmail.com>"]

[dependencies]
env_logger = "0.3"
log = "0.3"
group-by = "1.0"
lazy_static = "1.0"
maplit = "1.0"
rand = "0.4"
