#![allow(non_camel_case_types)]
#![allow(unused_imports)]

#[derive(Eq, PartialEq, PartialOrd, Ord, Hash, Copy, Clone, Debug)]
pub enum Location2 {
  TempOverworld1,
  TempOverworld2,
  TempOverworld3,
  TempOverworld4,
  TempOverworld5,
  TempOverworld6,
  TempOverworld7,
  TempOverworld8,
  TempOverworld9,
  TempOverworld10,
  TempOverworld11,
  TempOverworld12,
  TempOverworld13,
  TempOverworld14,
  TempOverworld15,
  TempOverworld16,
  TempOverworld17,
  TempOverworld18,
  TempOverworld19,
  TempOverworld20,

  EasternPalaceCompassChest,
  EasternPalaceBigChest,
  EasternPalaceCannonballChest,
  EasternPalaceBigKeyChest,
  EasternPalaceMapChest,
  EasternPalaceKeyPot,
  EasternPalaceKeyEyegore,
  EasternPalaceArmosKnights,
  EasternPalacePrize,

  DesertPalaceMapChest,
  DesertPalaceTorch,
  DesertPalaceBigKeyChest,
  DesertPalaceCompassChest,
  DesertPalaceBigChest,
  DesertPalaceKeyPotA,
  DesertPalaceKeyPotB,
  DesertPalaceKeyPotC,
  DesertPalaceLanmolas,
  DesertPalacePrize,

  TowerOfHeraMapChest,
  TowerOfHeraBasementCage,
  TowerOfHeraBigKeyChest,
  TowerOfHeraCompassChest,
  TowerOfHeraBigChest,
  TowerOfHeraMoldorm,
  TowerOfHeraPrize,

  PalaceOfDarknessBigKeyChest,
  PalaceOfDarknessTheArenaLedge,
  PalaceOfDarknessTheArenaBridge,
  PalaceOfDarknessBigChest,
  PalaceOfDarknessCompassChest,
  PalaceOfDarknessHarmlessHellway,
  PalaceOfDarknessStalfosBasement,
  PalaceOfDarknessDarkBasementLeft,
  PalaceOfDarknessDarkBasementRight,
  PalaceOfDarknessMapChest,
  PalaceOfDarknessDarkMazeTop,
  PalaceOfDarknessDarkMazeBottom,
  PalaceOfDarknessShooterRoom,
  PalaceOfDarknessHelmasaurKing,
  PalaceOfDarknessPrize,

  SwampPalaceEntrance,
  SwampPalaceBigChest,
  SwampPalaceBigKeyChest,
  SwampPalaceMapChest,
  SwampPalaceWestChest,
  SwampPalaceCompassChest,
  SwampPalaceFloodedRoomLeft,
  SwampPalaceFloodedRoomRight,
  SwampPalaceWaterfallRoom,
  SwampPalaceKeySkullA,
  SwampPalaceKeySkullB,
  SwampPalaceKeySkullC,
  SwampPalaceKeySkullD,
  SwampPalaceKeySkullE,
  SwampPalaceArrghus,
  SwampPalacePrize,

  IcePalacePrize,
  MiseryMirePrize,
  SkullWoodsPrize,
  ThievesTownPrize,
  TurtleRockPrize,
}
pub use self::Location2::*;

pub fn get_all_locations() -> Vec<Location2> {
  vec![
    TempOverworld1,
    TempOverworld2,
    TempOverworld3,
    TempOverworld4,
    TempOverworld5,
    TempOverworld6,
    TempOverworld7,
    TempOverworld8,
    TempOverworld9,
    TempOverworld10,
    TempOverworld11,
    TempOverworld12,
    TempOverworld13,
    TempOverworld14,
    TempOverworld15,
    TempOverworld16,
    TempOverworld17,
    TempOverworld18,
    TempOverworld19,
    TempOverworld20,

    EasternPalaceCompassChest,
    EasternPalaceBigChest,
    EasternPalaceCannonballChest,
    EasternPalaceBigKeyChest,
    EasternPalaceMapChest,
    EasternPalaceKeyPot,
    EasternPalaceKeyEyegore,
    EasternPalaceArmosKnights,
    EasternPalacePrize,

    DesertPalaceMapChest,
    DesertPalaceTorch,
    DesertPalaceBigKeyChest,
    DesertPalaceCompassChest,
    DesertPalaceBigChest,
    DesertPalaceKeyPotA,
    DesertPalaceKeyPotB,
    DesertPalaceKeyPotC,
    DesertPalaceLanmolas,
    DesertPalacePrize,

    TowerOfHeraMapChest,
    TowerOfHeraBasementCage,
    TowerOfHeraBigKeyChest,
    TowerOfHeraCompassChest,
    TowerOfHeraBigChest,
    TowerOfHeraMoldorm,
    TowerOfHeraPrize,

    PalaceOfDarknessBigKeyChest,
    PalaceOfDarknessTheArenaLedge,
    PalaceOfDarknessTheArenaBridge,
    PalaceOfDarknessBigChest,
    PalaceOfDarknessCompassChest,
    PalaceOfDarknessHarmlessHellway,
    PalaceOfDarknessStalfosBasement,
    PalaceOfDarknessDarkBasementLeft,
    PalaceOfDarknessDarkBasementRight,
    PalaceOfDarknessMapChest,
    PalaceOfDarknessDarkMazeTop,
    PalaceOfDarknessDarkMazeBottom,
    PalaceOfDarknessShooterRoom,
    PalaceOfDarknessHelmasaurKing,
    PalaceOfDarknessPrize,

    SwampPalaceEntrance,
    SwampPalaceBigChest,
    SwampPalaceBigKeyChest,
    SwampPalaceMapChest,
    SwampPalaceWestChest,
    SwampPalaceCompassChest,
    SwampPalaceFloodedRoomLeft,
    SwampPalaceFloodedRoomRight,
    SwampPalaceWaterfallRoom,
    SwampPalaceKeySkullA,
    SwampPalaceKeySkullB,
    SwampPalaceKeySkullC,
    SwampPalaceKeySkullD,
    SwampPalaceKeySkullE,
    SwampPalaceArrghus,
    SwampPalacePrize,

    IcePalacePrize,
    MiseryMirePrize,
    SkullWoodsPrize,
    ThievesTownPrize,
    TurtleRockPrize,
  ]
}
